### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by alexis-** [alessivs/supermemo-wine#1]
Would you like to transfer this repo to the [SuperMemo organization](https://github.com/supermemo) ? I think this is justified as this relates to SuperMemo and could help other users discover your project. I hope this doesn't come across the wrong way, as in a desire to take credit for your work. You would, of course, retain all accreditation.

I've been considering creating a mirror but it would require keeping tabs on the repository and pulling on every new push to upstream. If that's a more acceptable solution for you, I could give you manage rights on the SuperMemo org mirror and let you pull every time you send a new update.

Thanks for your efforts on this, this is a wonderful contribution.

**Comment by alessivs** [comment]
I appreciate the invitation, but say no to transfer. Because:

- I'm pretty sure of the benevolent intentions behind the org, and the usefulness of the software, but I am uneasy of the possibility of this being under the plain _SuperMemo_ moniker without their endorsement (I guess a good reason to take up this name must have existed).
- The more important aspect besides my subjective uneasiness, is that the Linux experience is really quirky. These installers yield potential for frustration if you're not careful or veered off guidelines, or simply because something changed in the behavior of one of the required tools. This is almost predestined to happen at some point. I would do a terrible favor to SuperMemo World/R&D to associate with it more frustration than there already is, or suggest that the platform is officially supported (which is not), especially to beginners, or people who do not read every warning.
- With organizations come leadership, rules, and by extension compliance with community guidelines / CoCs (my impression is that these are only written by lunatics).
- I don't remember if a mirror has a specific meaning in Git, but I consider this repo a mirror itself (of my local copy). GitHub was considered for its visibility only. I happily use my account to watch other projects, because of some package manager requires it, or some service asks for my credentials, but the product hasn't advanced despite enormous funding. Politics are expensive.

Regarding mirroring, _must_ it reside under the _SuperMemo_ org? Perhaps there is a clear advantage of e.g. eventually having to forward or triage any received issue reports on a platform its members and users (telling from the nature of the software under its umbrella) don't primarily use SM with? 

Regarding popularity and discoverability: If a user is split between Windows and Linux, I'd much prefer he uses SM on Windows, as it's better supported (and now has fresh 3rd party companion software). It better remain discoverable for people who are already looking for SM on Linux. It helps having decent placement on Google Search and links to and from SMpedia.

**Comment by alessivs** [comment]
If my stance is judged as defensive, understand the implications of the options suggested:

**Transfer to an organization** (_fromage_)

- and give up my ownership and downgrade my current role to an administrative one (plus textual _accreditation_);
- when none of the people in the organization have had involvement or contributions, nor signals they are actual users;
- when there are no signs I left this unmaintained (I use it myself);
- and no questions about my own plans.

If we hadn't had prior interaction, this would border on disrespect.

**Mirroring** (_dessert_)

- and having to push to the mirror;
- when it has enough visibility (search engines, inbound links) as-is;
- `alessivs/supermemo-wine` isn't bad or misleading, and clearly identifies who's responsible;
- for what? absorption into a namesake? the suggested mirror under `supermemo/` actually dillutes responsibility–possibly conflating it with another long-standing organization bearing the same name, an undesirable effect given the status of unsupported platform these installers run on.

_Aucun !_ (none)

My proactive and well-meaning suggestion is to link to it. supermemo/Issues#20 may be useful with other projects and resources that aren't acquirable.

**Comment by alexis-** [comment]
Hi alessio,

I appreciate your taking the time to formulate a detailed reply, even though it fiercely differs from what I expected. I will try to be equally thorough, let me know if I missed anything.

> I appreciate the invitation, but say no to transfer. Because:
> 
>     * I'm pretty sure of the benevolent intentions behind the org, and the usefulness of the software, but I am uneasy of the possibility of this being under the plain _SuperMemo_ moniker without their endorsement (I guess a good reason to take up this name must have existed).
I understand and approve of your concern. That is the reason why I reached out to Woz last year to ask for permission.

> 
>     * The more important aspect besides my subjective uneasiness, is that the Linux experience is really quirky. These installers yield potential for frustration if you're not careful or veered off guidelines, or simply because something changed in the behavior of one of the required tools. This is almost predestined to happen at some point. I would do a terrible favor to SuperMemo World/R&D to associate with it more frustration than there already is, or suggest that the platform is officially supported (which it is not), especially to beginners, or people who do not read every warning.
This is an important consideration. I believe I can safely assert that nobody in the SuperMemo GitHub organization ("supermemo.wiki") would satisfy themselves with leaving a stain on SuperMemo's reputation.

However, I have yet to meet a user who misrepresented supermemo.wiki or any of its subcomponents for an official authority. Should it turn out to be an issue, there are steps which can be taken to make it even more clear.

I would argue that no matter how cautious you are, there will always be individuals to vandalize that which is good, and that the benefits of spreading knowledge on using SuperMemo with Linux far outweigh the risk of having a handful of naysayers.

> 
>     * With organizations come leadership, rules, and by extension compliance with community guidelines / CoCs (my impression is that these are only written by lunatics).
I expected this uncertainty to be a concern for you, following our previous discussions about a certain dictatorship. Hence the solution of a mirror.

To that I will add that SuperMemo.wiki is handled in a very different spirit. One of the first word of order was to enable the community to vote on issues and important decisions. It is still a budding experiment, but I have high hopes for it.

> 
>     * I don't remember if a mirror has a specific meaning in Git, but I consider this repo a mirror itself (of my local copy). GitHub was considered for its visibility only. I happily use my account to watch other projects, because of some package manager requires it, or some service asks for my credentials, but the product hasn't advanced (...snip...) [my involvement with GitHub will likely have to increase].
We both are computer literate, and as such using GitHub facilities to monitor a project does not pose a problem for us. But by no mean is this a skill equally shared amongst SuperMemo users, or even computer users for that matter.

> 
> 
> Regarding mirroring, _must_ it reside under the _SuperMemo_ org? Perhaps there is a clear advantage to e.g. eventually having to forward or triage any received issue reports on a platform its members and users (telling from the nature of the software under its umbrella) don't primarily use SM with?
I assume you are speaking of SuperMemo Assistant ? Why not say the name ?
The SuperMemo GitHub isn't dedicated to SuperMemo Assistant. There are several other projects the organization caters for.

SuperMemo.wiki's (of which GitHub and SMA are a part) *"[manifest destiny](https://en.wikipedia.org/wiki/Manifest_destiny)"* `(a sense of mission to redeem the Old World by high example)` is to research and demonstrate the beneficial nature of SuperMemo's philosophy on human progress. SuperMemo the software is essential to catalyzing that progress, and as such is an integral part of the project.

> Furthermore, what's with the desire to enclose everything (particularly, something ye are unlikely to be using right now) under a single entity / community anyway? Projects and resources with independent direction have existed and will continue to exist.
I wholeheartedly support the need for borders\*\*, especially in our present time. They are as essential to the wellbeing of living organisms as they are to that of communities. However, let's not pretend that all federating undertakings are necessarily evil. SuperMemo, in its broad sense, has historically almost always been fragmented. And what good has it done ?

SuperMemo.wiki is trying to reconcile the jigsaw puzzle of SuperMemo so that it may be more accessible, and give more credence to its claims (yes, appearances matter, a lot).

I will also point to the fact that the [SuperMemo reddit](https://www.reddit.com/r/SuperMemo/) presently has 188 members, and the [Super_Memo reddit](https://www.reddit.com/r/super_memo/) 208. While this is a slightly superior number, I would like to stress the abysmal gap in content quality that these two subreddit offers. Without a doubt, the efforts you have put in /r/super_memo explain its higher frequentation. But only barely so. And all that /r/supermemo has to show for itself is its name.

\*\*: no connection with the American-Mexican border wall project, just in case.

> 
> Regarding popularity and discoverability: If a user is split between Windows and Linux, I'd much prefer he uses SM on Windows, as it's better supported (and now has fresh 3rd party companion software). But...it better remains discoverable for people who are already looking for SM on Linux. So it currently helps having decent placement on Google searches for "SuperMemo on Linux" and links to and from SMpedia.
Fair enough. But this isn't antagonistic with the proposal.

> 
> 
> If my stance is judged as defensive, understand the implications of the options suggested:
> 
> **Transfer to an organization** (_fromage_)
> 
>     * and give up my ownership and downgrade my current role to an administrative one (plus textual _accreditation_);
This is a valid concern. While we have past interactions, we aren't close friends or colleagues, and I am the owner of the SuperMemo GitHub organization. Even though it is obviously not my intention to harm supermemo-wine, or to claim the credit for myself, you have no way of knowing that for sure.

I will however point to the fact that I haven't taken credit for any of the projects under SuperMemo.wiki. These are undertakings I have been working on for 2 years now. I have invested entire months of my life in bringing them to life, from the ground up, for free (actually even a substantial deficit), and for the sole purpose of making SuperMemo better, and should I be so lucky, contribute ever so slightly to human progress.

This is factual, and I believe this is the strongest argument I could possibly make to demonstrate my benevolent intentions.

> 
>     * when none of the people in the organization have had involvement or contributions, nor signals they are actual users;
I do not understand how is this relevant to the proposal. Were any of the organization's official member using supermemo-wine, how would that make any difference to the legitimacy of the offer ?

> 
>     * when there are no signs I left this unmaintained (I use it myself);
Again, I do not see how this is relevant. If you left supermemo-wine unmaintained, I would simply have forked it. This is completely offtopic.

> 
>     * and no questions about my own plans.
This is really a low blow. We haven't even had the opportunity to start a discussion that already you are accusing me of this. And since you are raising this topic, I tried to reach out to you on Reddit several weeks ago (more on that later).

> 
> 
> If we hadn't had prior interaction, this would border on disrespect.
But we did. So why bring this up ? Rhetorical device ? A mean to show your discontentment that I dared advance a proposition which evidently doesn't suit you ?

And again, I did try to initiate a conversation several weeks prior to this proposal.

> 
> **Mirroring** (_dessert_)
> 
>     * and having to push/pull in an additional administrative step, deemed as a _solution_ to a nonsensical invented problem;
If you go that way we could also argue that the fact SuperMemo is inaccessible to the majority of the world's population isn't a loss either.

> 
>     * when the project has enough visibility (search engines, inbound links) as-is;
And yet, at the same time you [open an issue](https://github.com/alessivs/supermemo-wine/issues/4) with the clear consequence of giving more visibility to supermemo-wine. I am not exactly sure how this straw shield will "protect" you from other ill-fated, nefarious merging ventures, or who else would be in a position to suggest such a thing for that matter ?

> 
>     * when `alessivs/supermemo-wine` isn't bad or misleading, and clearly identifies who's responsible;
That was never put in question.

> 
>     * for what? absorption into a namesake? the suggested mirror under `supermemo/` actually dillutes responsibility–possibly conflating it with another long-standing organization bearing the same name, an undesirable effect given the status of unsupported platform these installers run on.
I have already adressed this previously.

> 
> 
> _Aucun !_ (none)
Fair enough, I respect your right to your opinion, and this is your work after all. It was unnecessary to take the high road to reach that conclusion.

> 
> My proactive and well-meaning suggestion is to link to it. [supermemo/Issues#20](https://github.com/supermemo/Issues/issues/20) may be useful with other projects and resources that aren't acquirable.

This is a much appreciated suggestion. I will address your proposal in the corresponding GitHub issue.

With all that being said, I would like to wrap up with the actual, larger intent of my reaching out to you in the first place (this issue, on Reddit).

There is no question that your numerous contributions throughout the years portray a clear desire to make SuperMemo a better software and a better community. I, for one, sorely regret your dissociation from the new "unofficial community" that has been slowly maturing since the advent of the SuperMemo Discord server.

Your work in /r/super_memo, supermemo-wine and the official supermemo wikis have helped progress SuperMemo as a whole. I have no doubt that you will continue with or without SuperMemo.wiki or me. What I am proposing is to pool our strengths and efforts together to try and create something even greater. I have already mentioned previously that we have many ongoing projects, some of which aligned with your documentation efforts on /r/super_memo. What have you got to lose to at least hear me out ?

I hope that these last paragraphs will help pave a way forward.

Alexis.

**Comment by alexis-** [comment]
*(reddit is currently experiencing some issues, and editing doesn't work. I deleted my original message to fix some types and presentation issues)*
Hi alessio,

I appreciate your taking the time to formulate a detailed reply, even though it fiercely differs from what I expected. I will try to be equally thorough, let me know if I missed anything.

> I appreciate the invitation, but say no to transfer. Because:
> 
> * I'm pretty sure of the benevolent intentions behind the org, and the usefulness of the software, but I am uneasy of the possibility of this being under the plain _SuperMemo_ moniker without their endorsement (I guess a good reason to take up this name must have existed).

I understand and approve of your concern. That is the reason why I reached out to Woz last year to ask for permission.

> 
> * The more important aspect besides my subjective uneasiness, is that the Linux experience is really quirky. These installers yield potential for frustration if you're not careful or veered off guidelines, or simply because something changed in the behavior of one of the required tools. This is almost predestined to happen at some point. I would do a terrible favor to SuperMemo World/R&D to associate with it more frustration than there already is, or suggest that the platform is officially supported (which it is not), especially to beginners, or people who do not read every warning.

This is an important consideration. I believe I can safely assert that nobody in the SuperMemo GitHub organization ("supermemo.wiki") would satisfy themselves with leaving a stain on SuperMemo's reputation.

However, I have yet to meet a user who misrepresented supermemo.wiki or any of its subcomponents for an official authority. Should it turn out to be an issue, there are steps which can be taken to make it even more clear.

I would argue that no matter how cautious you are, there will always be individuals to vandalize that which is good, and that the benefits of spreading knowledge on using SuperMemo with Linux far outweigh the risk of having a handful of naysayers.

> 
> * With organizations come leadership, rules, and by extension compliance with community guidelines / CoCs (my impression is that these are only written by lunatics).

I expected this uncertainty to be a concern for you, following our previous discussions about a certain dictatorship. Hence the solution of a mirror.

To that I will add that SuperMemo.wiki is handled in a very different spirit. One of the first word of order was to enable the community to vote on issues and important decisions. It is still a budding experiment, but I have high hopes for it.

> 
> * I don't remember if a mirror has a specific meaning in Git, but I consider this repo a mirror itself (of my local copy). GitHub was considered for its visibility only. I happily use my account to watch other projects, because of some package manager requires it, or some service asks for my credentials, but the product hasn't advanced (...snip...) [my involvement with GitHub will likely have to increase].

We are both computer literate, and as such using GitHub facilities to monitor a project does not pose a problem for us. But by no mean is this a skill equally shared amongst SuperMemo users, or even computer users for that matter.

> 
> 
> Regarding mirroring, _must_ it reside under the _SuperMemo_ org? Perhaps there is a clear advantage to e.g. eventually having to forward or triage any received issue reports on a platform its members and users (telling from the nature of the software under its umbrella) don't primarily use SM with?

I assume you are speaking of SuperMemo Assistant ? Why not say the name ?
The SuperMemo GitHub isn't dedicated to SuperMemo Assistant. There are several other projects the organization caters for.

SuperMemo.wiki's (of which GitHub and SMA are a part) *"[manifest destiny](https://en.wikipedia.org/wiki/Manifest_destiny)"* `(a sense of mission to redeem the Old World by high example)` is to research and demonstrate the beneficial nature of SuperMemo's philosophy on human progress. SuperMemo the software is essential to catalyzing that progress, and as such is an integral part of the project.

> Furthermore, what's with the desire to enclose everything (particularly, something ye are unlikely to be using right now) under a single entity / community anyway? Projects and resources with independent direction have existed and will continue to exist.

I wholeheartedly support the need for borders\*\*, especially in our present time. They are as essential to the wellbeing of living organisms as they are to that of communities. However, let's not pretend that all federating undertakings are necessarily evil. SuperMemo, in its broad sense, has historically almost always been fragmented. And what good has it done ?

SuperMemo.wiki is trying to reconcile the jigsaw puzzle of SuperMemo so that it may be more accessible, and to give more credence to its claims (yes, appearances matter, a lot).

I will also point to the fact that the [SuperMemo reddit](https://www.reddit.com/r/SuperMemo/) presently has 188 members, and the [Super_Memo reddit](https://www.reddit.com/r/super_memo/) 208. While this is a slightly superior number, I would like to stress the abysmal gap in content quality that these two subreddits offer. Without a doubt, the efforts you have put in /r/super_memo explain its higher frequentation. But only barely so. And all that /r/supermemo has to show for itself is its name.

\*\*: no connection with the American-Mexican border wall project, just in case.

> 
> Regarding popularity and discoverability: If a user is split between Windows and Linux, I'd much prefer he uses SM on Windows, as it's better supported (and now has fresh 3rd party companion software). But...it better remains discoverable for people who are already looking for SM on Linux. So it currently helps having decent placement on Google searches for "SuperMemo on Linux" and links to and from SMpedia.

Fair enough. But this isn't antagonistic with the proposal.

> 
> 
> If my stance is judged as defensive, understand the implications of the options suggested:
> 
> **Transfer to an organization** (_fromage_)
> 
> * and give up my ownership and downgrade my current role to an administrative one (plus textual _accreditation_);

This is a valid concern. While we have past interactions, we aren't close friends or colleagues, and I am the owner of the SuperMemo GitHub organization. Even though it is obviously not my intention to harm supermemo-wine, or to claim the credit for myself, you have no way of knowing that for sure.

I will however point to the fact that I haven't taken credit for any of the projects under SuperMemo.wiki. These are undertakings I have been working on for 2 years now. I have invested entire months of my life in bringing them to life, from the ground up, for free (actually even a substantial deficit), and for the sole purpose of making SuperMemo better, and should I be so lucky, contribute ever so slightly to human progress.

This is factual, and I believe this is the strongest argument I could possibly make to demonstrate my benevolent intentions.

> 
> * when none of the people in the organization have had involvement or contributions, nor signals they are actual users;

I do not understand how is this relevant to the proposal. Were any of the organization's official member using supermemo-wine, how would that make any difference to the legitimacy of the offer ?

> 
> * when there are no signs I left this unmaintained (I use it myself);

Again, I do not see how this is relevant. If you left supermemo-wine unmaintained, I would simply have forked it. This is completely offtopic.

> 
> * and no questions about my own plans.

This is really a low blow. We haven't even had the opportunity to start a discussion that already you are accusing me of this. And since you are raising this topic, I tried to reach out to you on Reddit several weeks ago (more on that later).

> 
> 
> If we hadn't had prior interaction, this would border on disrespect.

But we did. So why bring this up ? Rhetorical device ? A mean to show your discontentment that I dared advance a proposition which evidently doesn't suit you ?

And again, I did try to initiate a conversation several weeks prior to this proposal.

> 
> **Mirroring** (_dessert_)
> 
> * and having to push/pull in an additional administrative step, deemed as a _solution_ to a nonsensical invented problem;

If you go that way we could also argue that the fact SuperMemo is inaccessible to the majority of the world's population isn't a loss either.

> 
> * when the project has enough visibility (search engines, inbound links) as-is;

And yet, at the same time you [open an issue](https://github.com/alessivs/supermemo-wine/issues/4) with the clear consequence of giving more visibility to supermemo-wine. I am not exactly sure how this straw shield will "protect" you from other ill-fated, nefarious merging ventures, or who else would be in a position to suggest such a thing for that matter ?

> 
> * when `alessivs/supermemo-wine` isn't bad or misleading, and clearly identifies who's responsible;

That was never put into question.

> 
> * for what? absorption into a namesake? the suggested mirror under `supermemo/` actually dillutes responsibility–possibly conflating it with another long-standing organization bearing the same name, an undesirable effect given the status of unsupported platform these installers run on.

I have already adressed this previously.

> 
> 
> _Aucun !_ (none)

Fair enough, I respect your right to your opinion, and this is your work after all. It was unnecessary to take the high road to reach that conclusion.

> 
> My proactive and well-meaning suggestion is to link to it. [supermemo/Issues#20](https://github.com/supermemo/Issues/issues/20) may be useful with other projects and resources that aren't acquirable.

This is a much appreciated suggestion. I will address your proposal in the corresponding GitHub issue.

With all that being said, I would like to wrap up with the actual, larger intent of my reaching out to you in the first place (this issue, on Reddit).

There is no question that your numerous contributions throughout the years portray a clear desire to make SuperMemo a better software and a better community. I, for one, sorely regret your dissociation from the new "unofficial community" that has been slowly maturing since the advent of the SuperMemo Discord server.

Your work in /r/super_memo, supermemo-wine and the official supermemo wikis have helped progress SuperMemo as a whole. I have no doubt that you will continue with or without SuperMemo.wiki or me. What I am proposing is to pool our strengths and efforts together to try and create something even greater. I have already mentioned previously that we have many ongoing projects, some of which aligned with your documentation efforts on /r/super_memo. What have you got to lose to at least hear me out ?

I hope that these last paragraphs will help pave a way forward.

Alexis.

**Comment by alessivs** [comment]
> This is a valid concern. While we have past interactions, we aren't close friends or colleagues, and I am the owner of the SuperMemo GitHub organization. Even though it is obviously not my intention to harm supermemo-wine, or to claim the credit for myself, you have no way of knowing that for sure.
> 
> I will however point to the fact that I haven't taken credit for any of the projects under SuperMemo.wiki. 

You know full well that taking credit for something doesn't equate to having ownership over it. Giving up my ownership of the repo to the organization you admittedly own affects the position in the GitHub network, the effective communication regarding who is responsible for it, and my own freedom to decide on its design and direction...it's not perfect, but it's something I researched, delivered in reproducible form, and whose quirks I suffer on a daily basis. I am probably one of the first to know if something doesn't work as intended, and in a position to either try to fix it, or document it. How is it justifiable that the best direction it can take moving forward is taking it away from me?

Gone are the days you made something, shared it with people for them to use, received feedback, and moved forward...perfectly or not, but all was good. Now, because of entitlement, I am in the need to argue that keeping ownership over a relatively well maintained repository is a good thing. It's surreal.

If you are worried for its future, know that I too have altruistic motives, just not the kind of altruism that has dispossessing consequences for others. `supermemo-wine` will be even easier to use, and it will be inserted in a more cohesive body of documents. Because of this, cohesiveness and integrity are important for me. It's only moving little by little. More on the reasons in a bit.

> These are undertakings I have been working on for 2 years now. I have invested entire months of my life in bringing them to life, from the ground up, for free (actually even a substantial deficit), and for the sole purpose of making SuperMemo better, and should I be so lucky, contribute ever so slightly to human progress.
> 
> This is factual, and I believe this is the strongest argument I could possibly make to demonstrate my benevolent intentions.

You are making an investment, subject to sacrifices, but which you chose freely, where you get to use your capital goods and abilities. My [circumstances](https://www.reddit.com/r/caregiving/) have caused me to deplete my savings, now living frugally on a dime, in a country that's slowly falling back to third-world category; I don't get to use my knowledge extensively, and can't possibly buy time off something else to make something with it (when I come back, I'll have to do lots of catch-up). With a portion of the little productive time that remains I have contributed what you've seen me do (perhaps it's insufficient, but it's what I can do). Even if I had unmatched executive capacity and unanimously righteous philosophy I wouldn't think of expropriating others of the ownership of their work.

(And enumerating good deeds is pointless; I could start on how in the past, when I had more time, I emailed people out of the blue in the Yahoo! Group days, only because I had just learned something about SM that answered their question that had gone unanswered in the list, or how I've helped people one-on-one over email or Reddit messages, etc.)

Is there a chance that you, convinced of the correctness of your approach, are crossing a limit?

>> when none of the people in the organization have had involvement or contributions, nor signals they are actual users;
> I do not understand how is this relevant to the proposal. Were any of the organization's official member using supermemo-wine, how would that make any difference to the legitimacy of the offer ?

The supposition is that if I made a terrible job, and members the organization were more familiar by doing most of the work, it would be debatable that in its best interest the organization could take ownership, so as to ease its progress. This is not the case.

>> when there are no signs I left this unmaintained (I use it myself);
> Again, I do not see how this is relevant. If you left supermemo-wine unmaintained, I would simply have forked it. This is completely offtopic.

Supposition is similar to the previous one.

>> and no questions about my own plans.
>
> This is really a low blow. We haven't even had the opportunity to start a discussion that already you are accusing me of this. And since you are raising this topic, I tried to reach out to you on Reddit several weeks ago (more on that later).

Was it chat? If so please don't contact me personally on reddit except over messages (if they happen to work). My email is also here and on SMpedia (it's going to change in March–will be updated). 

> We are both computer literate, and as such using GitHub facilities to monitor a project does not pose a problem for us. But by no mean is this a skill equally shared amongst SuperMemo users, or even computer users for that matter.

`supermemo-wine` specifically will be friendlier and will have a better-accessible home, not just for git geeks. Read on.

>> If we hadn't had prior interaction, this would border on disrespect.
> But we did. So why bring this up ? Rhetorical device ? A mean to show your discontentment that I dared advance a proposition which evidently doesn't suit you ?

Would you be surprised if your dispossessing approach was considered disrespectful?

And of course your proposition doesn't suit me. I started `supermemo-wine`; it is a part of my approach to SuperMemo; there are cooperating developments, which are going to have a canonical home, publicly accessible for others to take bits of it to benefit from, but understandable as a cohesive body instead of subjected to an organization committee, or wikified. These have been my plans. How capricious of me, right?

> If you go that way we could also argue that the fact SuperMemo is inaccessible to the majority of the world's population isn't a loss either.
>
>  SuperMemo, in its broad sense, has historically almost always been fragmented. And what good has it done ?

The good is done to the cultivators of its philosophy who put the time to benefit from the method. Because this good occurs in a private sphere, it does not manifest in broad light for others to see. One can create perfectly friendly documentation, but the concrete benefits are only reaped by hard work, progressive internalization, and discipline. And you know the hurdles in teaching discipline. In addition, not every successful user is altruistic or otherwise shares the good with others (maybe it just doesn't occur to them), and for those who do, consider that in my experience between:

1. Dealing with life struggles
2. Using SuperMemo in earnest
3. Benefit the community of users

I can only usually choose two and remain good at it. Perhaps this is a similar situation for others.

> I will also point to the fact that the SuperMemo reddit presently has 188 members, and the Super_Memo reddit 208. While this is a slightly superior number, I would like to stress the abysmal gap in content quality that these two subreddits offer. Without a doubt, the efforts you have put in /r/super_memo explain its higher frequentation. But only barely so. And all that /r/supermemo has to show for itself is its name.

Too bad for the name. One significant observation is that `/r/super_memo`, being a casual aggregator and discussion/Q-A place, remains freedom-respecting, not pretending to embody a philosophy. It's a joy to participate in. (BTW, I'm only a moderator; the leading force continues to be @MasterHowToLearn).

> SuperMemo.wiki's (of which GitHub and SMA are a part) "manifest destiny" (a sense of mission to redeem the Old World by high example) is to research and demonstrate the beneficial nature of SuperMemo's philosophy on human progress. SuperMemo the software is essential to catalyzing that progress, and as such is an integral part of the project.
>
> SuperMemo.wiki is trying to reconcile the jigsaw puzzle of SuperMemo so that it may be more accessible, and to give more credence to its claims (yes, appearances matter, a lot).

Regarding the possibility I am contributing to the jigsaw puzzle characterization, does it cross your mind that I work better in a personal capacity–due in part to my [circumstances](https://www.reddit.com/r/caregiving/), and partly due to my innate way of work, and independence of thought and initiative? (I am not a medieval guild, and I am not Nicolas Bourbaki).

Some things are better wikified or handed over to an organization. But there are things–mostly personal initiatives in a creative space–which are not, because they are actually disturbed by imperfect or uninformed group decision processes. Even voting has to be implemented with care; it can easily suppress or silence brilliant independent thought in favor of irreflexive majority mobs.

I haven't read any major works by him, but Jaron Lanier's insights resonate well with me: [Digital Maoism: The Hazards of the New Online Collectivism](https://www.edge.org/conversation/jaron_lanier-digital-maoism-the-hazards-of-the-new-online-collectivism).

Does it also cross your mind that by pushing your proposal to either hand over my ownership, or absorb it into the SuperMemo org as a mirror, you are creating unnecessary friction (with me and for me, basically) that's going to affect my willingness to benefit the community you seek to benefit as well? (You can freely say it's not your problem, but that's the obvious effect.) You know that creativity needs a good brain environment[[1]](https://supermemo.guru/wiki/Natural_creativity_cycle)[[2]](https://supermemo.guru/wiki/Stress_resilience), and this friction doesn't contribute to it.

If Woz agreed to lend the SuperMemo name for the initiative, would he also approve of this initiative being expropriatory in intention, and disrespectful to the freedom of others?

This is [Hugo Chávez, expropriating others](https://www.youtube.com/watch?v=ErHuqCB5TDc). He's not you, but don't be like him.

> I, for one, sorely regret your dissociation from the new "unofficial community" that has been slowly maturing since the advent of the SuperMemo Discord server.
>
> Your work in /r/super_memo, supermemo-wine and the official supermemo wikis have helped progress SuperMemo as a whole. I have no doubt that you will continue with or without SuperMemo.wiki or me. What I am proposing is to pool our strengths and efforts together to try and create something even greater. I have already mentioned previously that we have many ongoing projects, some of which aligned with your documentation efforts on /r/super_memo. What have you got to lose to at least hear me out ?

To talk about a dissociation is premature. Also, do not picture me as an antagonist to the initiative only because of my negative towards your proposals. Do realize, though, that this push for giving up or absorbing my humble work in its name is not the best invitation. Please, desist over the presented proposals, and let me elaborate and contribute the way I know it's best for me, and still helps others.
