### ISSUE TITLE
phonetic font is not displayed correctly

### ISSUE THREAD

**Issue by Golddouble** [alessivs/supermemo-wine#14]
**How it looks:**
![SM phonetic font](https://user-images.githubusercontent.com/13977359/82878758-3c7e8480-9f3c-11ea-9980-33f46c33e3eb.png)

The content of the html component with shift+Ctrl+F6:
```
<HTML><HEAD></HEAD>
<BODY BORDER-BOTTOM: blue thin solid; BORDER-LEFT: blue thin solid; OVERFLOW: auto; BORDER-TOP: blue thin solid; BORDER-RIGHT: blue thin solid">Cyprus <SPAN style="WIDOWS: 2; TEXT-TRANSFORM: none; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; BORDER-COLLAPSE: separate; FONT: 14px Tahoma, Verdana, 'Lucida Sans Unicode', 'Segoe UI', 'Palatino Linotype', 'Arial Unicode MS', sans-serif; WHITE-SPACE: normal; ORPHANS: 2; LETTER-SPACING: normal; COLOR: rgb(0,0,0); WORD-SPACING: 0px; -webkit-border-horizontal-spacing: 0px; -webkit-border-vertical-spacing: 0px; -webkit-text-decorations-in-effect: none; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px" class=Apple-style-span>[Lgdt: 'sa<FONT face="lucida sans unicode">&#618;</FONT>pr&#601;s]<SPAN class=Apple-converted-space>&nbsp;</SPAN></SPAN></BODY></HTML>
```

**Comment by alessivs** [comment]
The HTML component source should perhaps read:

```
<BODY BORDER-BOTTOM: blue thin solid; BORDER-LEFT: blue thin solid; OVERFLOW: auto; BORDER-TOP: blue thin solid; BORDER-RIGHT: blue thin solid">Cyprus <SPAN style="WIDOWS: 2; TEXT-TRANSFORM: none; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; BORDER-COLLAPSE: separate; FONT: 14px Tahoma, Verdana, 'Lucida Sans Unicode', 'Segoe UI', 'Palatino Linotype', 'Arial Unicode MS', sans-serif; WHITE-SPACE: normal; ORPHANS: 2; LETTER-SPACING: normal; COLOR: rgb(0,0,0); WORD-SPACING: 0px; -webkit-border-horizontal-spacing: 0px; -webkit-border-vertical-spacing: 0px; -webkit-text-decorations-in-effect: none; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px" class=Apple-style-span>[Lgdt: 'sa<FONT face="lucida sans unicode">&#618;</FONT>pr<FONT face="lucida sans unicode">&#601;</FONT>s]<SPAN class=Apple-converted-space>&nbsp;</SPAN></SPAN></BODY></HTML>
```
The key part being: `pr<FONT face="lucida sans unicode">&#601;</FONT>s`, which encloses **ə** between `<FONT face="lucida sans unicode"></FONT>`.

To prevent partial formatting, I would recommend applying the Unicode font to all of the IPA expression between brackets.

**Side remark:** I do have items like this. They shared the same structure, so I opted to create a new HTML component containing only the IPA pronunciation with a new Style using a [Linux] system font (Wine applications can use both Microsoft and regular system fonts available on the Linux host).  A separate IPA component might not fit your use case, but it simplified formatting aspects for me (no need to select the IPA fragment and apply a new font to it).

And for the record, the font I used is [Doulos SIL](https://software.sil.org/doulos/) ([Andika SIL](https://software.sil.org/andika/) is also a good alternative – they even may be packaged for your distro already).

**Comment by Golddouble** [comment]
Thank you.

-How did I create my phonetic words?
Answer: I just copied them out from "Goldendict"-dictionary. 

-I have a lot of such phonetic words in my collection. I can convert such words, when I mark them and then apply the font "lucida sans unicode" to it in the GUI. Is this what you are suggesting? Seems I have to convert each of them? 

-I do still not understand, why this works in windows, but not in wine. I'm surprised. Has this something to do with the word "webkit"? Should webkit also be installed in wine?

-I have tried to make a component with style with "lucida sans unicode". But still not all phonetic characters are displayed correctly.

**Comment by alessivs** [comment]
When you copy rendered HTML text from webkit based browsers such as Chromium (or webkit-based webviews inside desktop programs such as QtWebkit or QtWebEngine–Goldendict depends on qt5-webkit) it is copied with webkit-specific styles and markup that is more polluted of styling directives than styles copied from Firefox/Gecko or Internet Explorer/Trident. This is irrespective of SuperMemo running under Wine or natively on Windows.

EDIT: for example, part of the above paragraph copied to the clipboard from Firefox:

```html
<meta http-equiv="content-type" content="text/html; charset=utf-8">
When you copy rendered HTML text from webkit based browsers such as 
```

and from Chromium

```html
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<span style="color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
When you copy rendered HTML text from webkit based browsers such as 
```

Some webkit-specific styles are ignored, but others are carried over to your SuperMemo HTML components as `style` attributes. When applying your own styles on top, some of them may not apply successfully because inline styling markup attributes have higher precedence than linked stylesheets. Before applying your own styles, filter out *Styles* and *Fonts* (use the Filter dialog–**F6** shortcut). Afterwards, apply your own styles.

An alternative to applying your own styles on top, is to modify the global SuperMemo CSS stylesheet (**Tools : Options : Fonts : Stylesheet**) and use an IPA-supporting font as the default text font. Then all you would have to do is clear (filter out) extraneous styles, so that the HTML falls back to your extended unicode font.

**Comment by Golddouble** [comment]
Thank you.
