### ISSUE TITLE
Goldendict <-> Supermem

### ISSUE THREAD

**Issue by Golddouble** [alessivs/supermemo-wine#17]
Do you use Goldendict together with Lutis-wine-Supermemo?
http://goldendict.org/wiki/index.php/Main_Page

If yes: Can you confirm that the scan function does not work, only Ctrl+C+C works? 

If yes: I guess there is no way to change that? Is it?

Thank you.

**Comment by alessivs** [comment]
1. I have Goldendict, but don't use it as often as I could. I learned of this
      tool thanks to your earlier report! Very convenient.

   2. This seems like a typical boundary limitation between X apps and Wine apps.

     2a. Linux-based Goldendict has no way of knowing that text has been
         selected. Unlike in X applications, selected text isn't copied to the
         Xorg PRIMARY selection (the one whose contents you paste using the
         middle mouse button), since that's not how Windows apps work.

     2b. The reason Ctrl+C Ctrl+C works across the boundary is that the first
         key chord effectively copies text to the Windows clipboard, which Wine
         has mapped to the Xorg CLIPBOARD selection, which Linux-based
         Goldendict is in turn monitoring for changes.

   3. So I have to conclude the scan feature is not supported across the boundary.

   4. [Note that Wine has a setting to use both PRIMARY and CLIPBOARD selections
      when copying something to the clipboard under Wine, but it doesn't change
      things as it still needs user interaction (Ctrl+C).]

**Comment by Golddouble** [comment]
Thank you.
