### ISSUE TITLE
Font size too small on HiDPI

### ISSUE THREAD

**Issue by song12301** [alessivs/supermemo-wine#23]
I have tried changing the display using winecfg per the supermemo linux wiki page recommendation, however that does not work.
Screenshot of Problem:
![Screenshot from 2021-02-16 20-57-05](https://user-images.githubusercontent.com/79387693/108613384-6e216f00-742c-11eb-964e-4af533c8ecba.png)
Furthermore, I am unable to change the interface font size to over 14 (although I can change the other types of font sizes). Maybe this has something to do with the issue?:
![Screenshot from 2021-02-16 20-57-14](https://user-images.githubusercontent.com/79387693/108613403-a32dc180-742c-11eb-92b1-3e440e5c86c7.png)
Any help is appreciated, thanks!

**Comment by alessivs** [comment]
> I have tried changing the display using winecfg per the supermemo linux wiki page recommendation

Do you mean [this recommendation](https://supermemopedia.com/wiki/SuperMemo_for_Windows_under_Wine#Fonts_and.2For_widgets_are_too_small)?

I would first tackle the system font DPI in Wine, and only then, the apparent font size limitation of the widgets controlled by SuperMemo.

From looking at the native font selection dialog as well as the menu bar font, it is possible that the DPI changes in `winecfg` didn't apply. Possible reasons:

* There were lingering Wine applications running in the prefix preventing the settings to "refresh"
* You are using a script or launcher with an overriding configuration.
* You are running `winecfg` in the default prefix instead of the SuperMemo prefix. Be sure the WINEPREFIX environment variable is set accordingly: `WINEPREFIX=/path/to/supermemo/prefix winecfg`

Would one of these be the case?

Note that hidpi support in Wine is limited to font size (AFAIK).

**Comment by song12301** [comment]
Thanks a lot! It was option 3.

I just ran WINEPREFIX=~/.local/share/wineprefixes/supermemo15/ winecfg, then increased the font in the graphics tab
