### ISSUE TITLE
command wine regedit C:/windows/Temp/set-tabprocgrowth.reg returned status 53. Aborting.

### ISSUE THREAD

**Issue by doesn123** [alessivs/supermemo-wine#24]
I get this error after running the second script.
Also - do I need to place sm18inst.exe somewhere specific?

I'm running Arch 64-bit, wine-6.6, winetricks: 20210206 - sha256sum
Thanks very much!

**Comment by alessivs** [comment]
Hi there! What's the command line you used?

**Comment by doesn123** [comment]
Thanks alessivs!
I was using Fish, I just tried with Bash.
Here's what I did:

rm ~/.local/share/wineprefixes/supermemo18 ~/.wine
env WINEARCH=win32 sh winetricks arch=32 prefix=supermemo18
sh winetricks prefix=supermemo18 supermemo18.verb

I again got the message (after the second command):
command wine regedit C:/windows/Temp/set-tabprocgrowth.reg returned status 53. Aborting

I should also mention I'm not using any Desktop Environment with Arch, but instead using dwm. Should SM be able to run without a DE?
Do I need to put the sm18inst.exe anywhere specific?

Ta!

**Comment by alessivs** [comment]
> I was using Fish, I just tried with Bash

Instructions (esp. regarding setting environment variables) are always assumed to be for POSIX shells. There should be no problem with the one-liner though.

> Here's what I did:

The installation aborts when installing the IE 8 verb (winetricks). There are reports that installation is broken in Wine 5.7+. Can you downgrade to an older Wine such as 5.2?

You would downgrade by:

- Downgrading wine-gecko and wine-mono according to tables[[1]](https://wiki.winehq.org/Gecko)[[2]](https://wiki.winehq.org/Mono)

```
wget https://archive.archlinux.org/packages/w/wine/wine-5.2-1-x86_64.pkg.tar.zst
wget https://archive.archlinux.org/packages/w/wine-gecko/wine-gecko-2.47.1-1-x86_64.pkg.tar.xz
wget https://archive.archlinux.org/packages/w/wine-mono/wine-mono-4.9.4-1-any.pkg.tar.xz

pacman -U wine-5.2-1-x86_64.pkg.tar.zst wine-gecko-2.47.1-1-x86_64.pkg.tar.xz wine-mono-4.9.4-1-any.pkg.tar.xz
```

- Adding entries in `/etc/pacman.conf`:

```
IgnorePkg = wine wine-mono wine-gecko
```

> using dwm. Should SM be able to run without a DE?

No problem. Just bear in mind:

* SuperMemo implements its own unruly window management. You can use `winecfg` to configure it to use a single desktop window, or use floating mode, or patch dwm.
  * Otherwise, the most SuperMemo-friendly WMs are Kwin and IceWM in my experience for multi-window operation.
* If text rendering is ugly without RGB anti-aliasing and lcdfilter (DEs tend to make this configuration straightforward), make sure to [configure it](https://wiki.archlinux.org/index.php/font_configuration). I have the configuration in two places (Arch), `~/.Xresources` and `~/.fonts.conf` – [example](https://gist.github.com/alessivs/a9907b0c2e1ad167ca922fef736410d3).

After successful installation, you would run `winecfg` like: `WINEPREFIX=~/.local/share/wineprefixes/supermemo18 winecfg`

>  Do I need to put the sm18inst.exe anywhere specific?

With the installer in this repository, if installation of required verbs (IE 8) is successful, you will be explicitly asked to copy the `sm18inst.exe` file to a specific location.

SuperMemo have since provided downloadable installers, and these verbs are slightly outdated (sorry about that, I struggle to make time to maintain stuff), but they still work provided the Wine edition is compatible. Subscribe to #25 or "watch" this repository to be notified of improvements...

**Comment by doesn123** [comment]
Thanks for your detailed and fast response alessivs.
Great to know about SM friendly windows managers and RGB anti-aliasing and lcdfilter etc..
Please excuse my lack of understanding, but I want to get this right!

In order to downgrade to 5.2 I assume I need to download the x86 files, 32-bit for both Gecko and Mono ('wine-5.0-rc1 - wine-5.22' and version '5.11' respectively).  
Should I download the .msi files or the tarball files and where should they be placed? 
For 'mono', does it matter whether I do a 'shared install' or 'prefix local install'? 
For 'gecko' I assume the file should be moved to /usr/share/wine/gecko?

Thanks very much, I've heard quite some users talk very highly of supermemo-wine and so looking forward to using it myself!

**Comment by alessivs** [comment]
> In order to downgrade to 5.2 I assume I need to download the x86 files, 32-bit for both Gecko and Mono ('wine-5.0-rc1 - wine-5.22' and version '5.11' respectively).
> Should I download the .msi files or the tarball files and where should they be placed?

They are packages–not tarballs, not installers. They're ready to use with `pacman -U` using exactly the sequence of commands I put in the code block (pacman -U must be performed as root, of course). They can be placed in any directory; ideally, download and run pacman from the same directory so you don't have to type paths.

> For 'mono', does it matter whether I do a 'shared install' or 'prefix local install'?

Again, these are system packages. The installation has system-wide implications and you are not given the option you mention.

> For 'gecko' I assume the file should be moved to /usr/share/wine/gecko?

No, just install with pacman and dispose or backup the downloaded packages at will.

----

For complete clarity (assuming you use `sudo` to gain privileges):

```sh
cd ~/Downloads
wget https://archive.archlinux.org/packages/w/wine/wine-5.2-1-x86_64.pkg.tar.zst
wget https://archive.archlinux.org/packages/w/wine-gecko/wine-gecko-2.47.1-1-x86_64.pkg.tar.xz
wget https://archive.archlinux.org/packages/w/wine-mono/wine-mono-4.9.4-1-any.pkg.tar.xz
sudo pacman -U wine-5.2-1-x86_64.pkg.tar.zst wine-gecko-2.47.1-1-x86_64.pkg.tar.xz wine-mono-4.9.4-1-any.pkg.tar.xz
```

**Comment by doesn123** [comment]
Thanks for the clarification. 
After the last command I got the following error message:

error: failed to commit transaction (conflicting files)
wine: /etc/fonts/conf.d/30-win32-aliases.conf exists in filesystem
wine-gecko: /usr/share/wine/gecko/wine-gecko-2.47.1-x86.msi exists in filesystem
Errors occurred, no packages were upgraded.

I (seemingly) solved this by consulting the wiki: "If the file is not owned by another package, rename the file which 'exists in filesystem' and re-issue the update command." - https://wiki.archlinux.org/index.php/Pacman#Troubleshooting

I'm now getting this error:

error: could not extract /usr/share/wine/gecko/wine-gecko-2.47.1-x86.msi (Lzma library error:  No progress is possible)
error: problem occurred while upgrading wine-gecko
error: could not commit transaction
error: failed to commit transaction (transaction aborted)
Errors occurred, no packages were upgraded.

I can only find an (unofficial) suggestion to: "Try to get another copy of the archive from wherever you got it from"
I tried replacing the .msi in question with one I downloaded from https://dl.winehq.org/wine/wine-gecko/2.47.1/ and ended up with the same error.

Any ideas?

**Comment by alessivs** [comment]
There should be no problem at all with the packages. I ran the commands myself; only had to rename `/etc/fonts/conf.d/30-win32-aliases.conf`.

Ideas:

* Just in case: `pacman -Syyu` (ensure you added the package names to /etc/pacman.conf's IgnorePkg section)
* Compare checksum:

```
sha256sum wine-gecko-2.47.1-1-x86_64.pkg.tar.xz
fb6b4cdfc334017806d38b40d49fccd8536dc5ffa3f701b2c499dbfff2fbd75c  wine-gecko-2.47.1-1-x86_64.pkg.tar.xz
```

The irony is that neither wine-gecko or wine-mono are needed for SuperMemo, but I do suggest to keep all three mutually compatible for consistency and the convenience to prevent auto download of the correct versions upon normal prefix creation.

**Comment by doesn123** [comment]
I ran pacman -Syyu and re-renamed '/etc/fonts/conf.d/30-win32-aliases.conf' and the second command worked! I now have Wine 5.2.
I managed to get the IE wizard to run although it ended without asking for sm18inst.exe. It seemed my internet had failed.
Once my internet was back up and running I tried it again and it went straight to asking me about sm18inst.exe (skipping the IE wizard).
The sm installer went smoothly and I've updated pacman.conf (I assume that will work with me using the Fish shell?) and also disabled 'manage file associations'.

I ran the command: env WINEPREFIX=~/.local/share/wineprefixes/supermemo18 wine ~/.local/share/wineprefixes/supermemo18/drive_c/SuperMemo/sm18.exe

and got the error: wine: invalid directory ~/.local/share/wineprefixes/supermemo18 in WINEPREFIX: not an absolute path.

using the answer [here](https://askubuntu.com/questions/738516/wine-not-working-error-invalid-directory-prefix32-in-wineprefix-not-an-abso#738533) I managed to get past it. I then got this (among other errors): err:module:__wine_process_init L"C:\\windows\\system32\\sm18.exe" not found.
I make a copy of sm.exe in the directory mentioned and tried again.
SM launched, but was very buggy. I kept getting the error message: 'Error setting HTML' and would beep when ever I clicked on anything.
I've also tried launching sm.exe with 'wine sm.exe' and it launches but I get the same bugs.

Presumably the sm install wizard should have directory launched after the IE wizard. Perhaps IE isn't installed?

**Comment by alessivs** [comment]
> env WINEPREFIX=~/.local/share/wineprefixes/supermemo18 wine ~/.local/share/wineprefixes/supermemo18/drive_c/SuperMemo/sm18.exe
> and got the error: wine: invalid directory ~/.local/share/wineprefixes/supermemo18 in WINEPREFIX: not an absolute path.

`wine` and `winetricks` are able to take environment variables from the invocation. `env` is intended for compatibility with other applications that may be involved in the one-liner.

Unfortunately, fish doesn't behave like the other shells. Simply strip *env*: `WINEPREFIX=<path> [...]`

> SM launched, but was very buggy. I kept getting the error message: 'Error setting HTML' and would beep when ever I clicked on anything

It is clearly because IE (provider of the MSHTML component needed to display HTML SM components) was not properly installed in the prefix you ran SM 18 from. Perhaps you ran SuperMemo unintendedly from a different Wine prefix.

Delete the Wine prefix folder: `rm -rf ~/.local/share/wineprefixes/supermemo18`

and re-run the installation. The download of IE8 should already be cached.

Also, note that during installation, you are asked to copy `sm18inst.exe`, not `sm18.exe` or any other file. The target folder is probably `~/.cache/winetricks/supermemo18/`.

The installation also copies a .desktop shortcut into your XDG menu (or the XDG desktop folder as a fallback) so that you don't need to explicitly run a command line to start SM. 

> Presumably the sm install wizard should have directory launched after the IE wizard.

If you haven't yet copied sm18inst.exe to the target folder, the Winetricks verb does–not the SM installer. The SM installer that runs afterwards is semi-unattended (makes clicks for you to omit installing a shortcut, because the verb creates its own). There will be an improvement introducing proper unattended mode in the next release.

**Comment by doesn123** [comment]
Success, the new sm collection works perfectly!

As I'm using dwm (doesn't appear to be supported by XDG) I assume instead I could just create an alias for the command to run SM?
After some playing around with the winecfg setting, sm's windows are working perfectly. The only thing is when opening some of my sm collections I believe a dialog box is opened behind the main window preventing me from clicking on anything - a common issue on Windows - do you know of how to access that dialog box? I had to quit X to close the window.

I assume it's best to use Windows 10 on the winecfg as sm is recommended to be run on Windows 10?
Thanks so very much for your time and patience alessivs! :)

**Comment by alessivs** [comment]
> As I'm using dwm (doesn't appear to be supported by XDG) I assume instead I could just create an alias for the command to run SM?

`dwm` works with `dmenu`, no? You can install [j4-dmenu-desktop](https://aur.archlinux.org/packages/j4-dmenu-desktop/) from the AUR to have it find those .desktop files.

You can also [run the desktop file](https://wiki.archlinux.org/index.php/Desktop_entries#Run_a_desktop_file_from_a_terminal) that the verb likely created in `~/.local/share/applications/`.

If that's still not your preference you can start SuperMemo with:

`WINEPREFIX=~/.local/share/wineprefixes/supermemo18/ wine "C:\\SuperMemo\\sm18.exe"` 

> After some playing around with the winecfg setting, sm's windows are working perfectly

I only have to add that you always prepend `winecfg` with the WINEPREFIX set, otherwise it will run under the default prefix (typically `~/.wine`).

> The only thing is when opening some of my sm collections I believe a dialog box is opened behind the main window preventing me from clicking on anything

It's possibly SuperMemo's own "desktop background". A couple window managers such as KWin don't map it, but most WMs display it as a separate window. You can hide it in SuperMemo *menu bar : Window : [ ] Background*.

Or you can run SuperMemo as a single Windows desktop window: `WINEPREFIX=~/.local/share/wineprefixes/supermemo18/ winecfg`, then *Graphics : [x] Emulate a virtual desktop* (and set a desktop size). Close all of the processes/windows running in the prefix and re-run SM.

**Comment by alessivs** [comment]
> I assume it's best to use Windows 10 on the winecfg as sm is recommended to be run on Windows 10?

**NO**. Leave it at Windows XP.

----

All your questions have been noted for a future guide / better documentation for Winetricks based installation.

**Comment by alessivs** [comment]
>> I assume it's best to use Windows 10 on the winecfg as sm is recommended to be run on Windows 10?

> NO. Leave it at Windows XP.

Next edition of the installers will take care of this automatically–the default Windows version can differ from what IE8 sees (XP).

**Comment by alessivs** [comment]
> wine regedit C:/windows/Temp/set-tabprocgrowth.reg returned status 53. Aborting.

Next release will be timed along the new Winetricks release that will merge a change that fixes IE application and components installation/operation for current Wine, so installing a prior Wine will not be needed on Arch (or one could go back to Wine stable, but not beyond that).
