### ISSUE TITLE
Screen-size problems/AHK scripts/problems with the toolbar

### ISSUE THREAD

**Issue by doesn123** [alessivs/supermemo-wine#28]
First of all, thanks very much for SuperMemo Wine - I've been using it for some time and its been working very well.

A few things I'd love to sort out:

- right-clicking a topic near the bottom or top of the screen will not re-adjust so that I can see all of the options but instead will disappear of the side of the screen (this means I can't use the process branch at all). Also some windows (The Element Priority window for example) opens far to the right and closer to the bottom that usual - I don't have any other screen-size related issues on my machine
- two of my older collections that I made on a previous Linux installation wont display '-' but instead displays '   ' (I made a new collection that doesn't share this problem) any ideas on how to remedy this?
- I've heard it's possible to use AHK scripts with SM Wine. Could you explain how it's possible to have them run alongside SM?
- on the toolbar there is a lot of text next to some of the icons which mean that many of the icons further to right (such as the concept registry) are not seen. The text next to Icons: ReplaceB; ToolsBtn; Command; Layout
- Is it possible to run SM directly from eshell? I run SM in Bash with: 'WINEPREFIX=~/.local/share/wineprefixes/supermemo18 wine ~/.local/share/wineprefixes/supermemo18/drive_c/SuperMemo/sm18.exe'
- just to let you know (this doesn't bother me at all) when navigating through the options in the drop down menus (File, Edit etc) the theme of the options that my cursor has passed over turns to a light theme

**Comment by alessivs** [comment]
>   * right-clicking a topic near the bottom or top of the screen will not
>     re-adjust so that I can see all of the options but instead will
>     disappear of the side of the screen (this means I can't use the
>     process branch at all). Also some windows (The Element Priority
>     window for example) opens far to the right and closer to the bottom
>     that usual - I don't have any other screen-size related issues on my
>     machine


I assume you're not using Wine desktop, but multi-window SuperMemo. This
seems to be window manager-dependent. A screenshot would be useful in
understanding your issue–though not necessarily leading to a solution.


>   * two of my older collections that I made on a previous Linux
>     installation wont display '-' but instead displays ' ' (I made a new
>     collection that doesn't share this problem) any ideas on how to
>     remedy this?

Display where exactly?


>   * I've heard it's possible to use AHK scripts with SM Wine. Could you
>     explain how it's possible to have them run alongside SM?

Yes, you can. I can't guarantee all kinds of scripts can run, because
Wine doesn't support the full Win32 API. You can install AHK with:

```
WINEPREFIX=/path/to/wine/prefix winetricks autohotkey
```

>   * on the toolbar there is a lot of text next to some of the icons
>     which mean that many of the icons further to right (such as the
>     concept registry) are not seen. The text next to Icons: ReplaceB;
>     ToolsBtn; Command; Layout

I have (undoable) binary patches for this, but they must be tailored
specifically for a given SuperMemo executable version. In case I don't
have a patch for a specific version, I can produce it on demand for any
SuperMemo executable (hex-editing by hand to preserve byte count and
byte position of everything else and thus avoid runtime crashes; I don't
know if I can automate it given that the byte position is different on
each compilation (Delphi)).

When this project is updated, I'll include them. Know that I didn't try
them in conjunction with the new SuperMemo 18 themes (but I'll look into
it). Leave a note stating which SuperMemo version you are using.

>   * Is it possible to run SM directly from eshell? I run SM in Bash
>     with: 'WINEPREFIX=~/.local/share/wineprefixes/supermemo18 wine
>     ~/.local/share/wineprefixes/supermemo18/drive_c/SuperMemo/sm18.exe'

Very possible. You can also run it right from elisp. I once did this:


```
(let ((process-environment (cons
                            (concat "WINEPREFIX=" (getenv "HOME")
"/.local/share/wineprefixes/sm18" " WINEARCH=win32")
                            process-environment)))
  (call-process-shell-command ...))
```

>   * just to let you know (this doesn't bother me at all) when navigating
>     through the options in the drop down menus (File, Edit etc) the
>     theme of the options that my cursor has passed over turns to a light
>     theme

The new SuperMemo 18 themes? I don't recommend them with Wine. Too many
glitches for the sake of cosmetics. I prefer native (Windows classic)
theming. EDIT: I have a project in progress regarding classic theming.

**Comment by doesn123** [comment]
I'm using EXWM and on the mode bar it says "Wine Desktop"  add photos

Sorry - I should've been more clear. I typed in 'one-two-three' and get 'one  two  three' instead

I've went through the AHK installer . I assume I use something similar to the command below to run it:
env WINEPREFIX=~/.local/share/wineprefixes/AHK/ autohotkey  "path/to/authotkey.exe"

- I can't find any .exe file.
- I assume each script needs to be run manually before starting SM? (using a bash script to do so for example). 

I'm using SuperMemo 18 - The patch sounds great - as long as it's safe! :)
Maybe I'll try to get by with the toolbar issue. The only thing I miss is not being able to set a new concept. But I believe right clicking on a topic and selecting 'Set Concept' does the same thing. 

I tried the below command (I assume that's what you meant?), but tries to do something but I end up having to kill the command.

(let ((process-environment (cons
                            (concat "WINEPREFIX=" (getenv "HOME")
"/.local/share/wineprefixes/sm18" " WINEARCH=win32")
                            process-environment)))
  (call-process-shell-command "WINEPREFIX=~/.local/share/wineprefixes/supermemo18 wine
     ~/.local/share/wineprefixes/supermemo18/drive_c/SuperMemo/sm18.exe"))

I'm using the Windows 10 Dark Theme - the other themes seem to 'revert' back to the 'Windows' theme when the mouse hovers over a menu item - photo attached

Photo also attached regarding windows (in this the Element Priority Window) opening not in the center

![IMG-0429](https://user-images.githubusercontent.com/77695594/121806276-1dd25500-cc47-11eb-94d9-0dcdac7e952f.jpg)
![IMG-0430](https://user-images.githubusercontent.com/77695594/121806282-2034af00-cc47-11eb-8309-cc8e259544dc.jpg)
![IMG-0432](https://user-images.githubusercontent.com/77695594/121806286-2165dc00-cc47-11eb-9858-9bbb7b842537.jpg)
![IMG-0433](https://user-images.githubusercontent.com/77695594/121806289-22970900-cc47-11eb-9c18-6df332a5ca00.jpg)
![IMG-0434](https://user-images.githubusercontent.com/77695594/121806297-2460cc80-cc47-11eb-83f8-8d870d432868.jpg)

**Comment by alessivs** [comment]
## Elisp
The snippet I posted would start a synchronous process, rather than async. I ended up not using EXWM for much too long, so I would need to revisit this. My emphasis is that's it's possible to manage the Wine process from elisp, but I didn't pursue it further, and I don't think I can provide support at this moment. Personally I alternate between [herbstluftwm](https://herbstluftwm.org/) (I have high hopes to manage multi-window SM with this wm, which I'm still learning) and [cwm](https://github.com/leahneukirchen/cwm), and haven't used EXWM in a long time.

## Theming and toolbar
It's possible that the custom theming introducing button labels is pushing toolbar buttons further to the right. Methinks patching would solve this. I also had a patch to introduce a keyboard shortcut to hit the default concept button.

Using any binary patch is a leap of faith. I aim to be transparent in my approach.

As for the apparent theme reversal on mouse hover...it's a shame, but it's what it is. *Themes* doesn't strike me as a killer feature. Little in v18 strikes me as a killer feature compared to v17.

## Window misplacement
- Popup windows not opening in the viewport
- Priority window apparently not opening in the center

It's very likely that the desktop window is larger in height than the viewport Emacs gives it. You'll have to configure the Wine desktop window so it has precise dimensions for your screen arrangement.

### Procedure
You can obtain the appropriate dimensions with the following method if there's not a better one.

1. Start an application occupying the full desired height (not the Wine desktop window, since the premise is that it's incorrectly sized)
2. Run from a terminal/shell (may be, e.g. tiled or floating): `xwininfo`
3. Click the graphical application
4. Obtain `Height:` from the command's output

`Width:` will usually be the full viewport width, which is likely known to you. But you can also arrange the window so it occupies the full desired width and obtain this value in the same way.

Now you can add this configuration:

1. **Via configuration, with `winecfg`**. 
  - `WINEPREFIX=/path/to/wine/prefix winecfg`
  - In the *Applications* tab, enter the values you obtained above next to *Desktop size*: `[width]` x `[height]`
2. **Via command line**
 - `WINEPREFIX=[...] wine explorer /desktop=SuperMemo,[width]x[height] "C:\\SuperMemo\\sm18.exe"` (*SuperMemo* is just an arbitrary desktop name)

[EDIT] Here's a snippet that may be useful to achieve the required WxH format:

```sh
xwininfo |
           sed -n -e '/^  Width: / {
                          s/.*: //;
                          h
                      }
                      /^  Height: / {
                          s/.*: //g;
                          H;
                          x;
                          s/\n/x/p
                      }'
```
([borrowed](https://github.com/herbstluftwm/herbstluftwm/blob/9853294098d6546998ae474dc39b2adea3355bb7/scripts/floatmon.sh#L11-L21))

## AutoHotKey
It's possible to run AHK scripts either before or after SuperMemo is started. The convenience depends on what you're trying to do:

* If you're managing SuperMemo starting from AHK then you'll have to invoke your script first, at which point the AHK script may be all you run if you start SuperMemo from it (e.g., with [Run](https://www.autohotkey.com/docs/commands/Run.htm))
* If you use AHK to interact with a running instance then you can start it afterwards.

In any case, do not create a separate wine prefix for AHK if you want both SM and AHK to interact. Reuse the SM prefix.

To start the resident application: `WINEPREFIX=[...] wine "C:\\Program Files\\AutoHotKey\\AutoHotKey.exe"`

By the way, to execute a given .ahk script, you can put `AutoHotKey.exe` anywhere on your file system really, inside or outside the prefix: `WINEPREFIX=[...] wine [/path/to/AutoHotKey.exe] [/path/to/your_script.ahk]`

Following the procedure of the previous section, you can ensure the existence of a system tray to interact with AHK's tray button when starting SuperMemo; give the desktop the `shell` name. It might not be actually needed:

`WINEPREFIX=[...] wine explorer /desktop=shell "C:\\SuperMemo\\sm18.exe"`

## Concept assignment vs linking

> The only thing I miss is not being able to set a new concept. But I believe right clicking on a topic and selecting 'Set Concept' does the same thing.

None of the following toolbar buttons replace the *Set concept* option:

```
[LinkConcept] [DefaultConcept]
```

- *LinkConcept* will add a linked concept for the purpose of Neural learning (it will not replace the primary concept group)
- *DefaultConcept* will set the concept for subsequently added elements (e.g. via Ctrl+N, Alt+N).

...whereas *Set concept* sets the concept group of the selected branch.

To set the concept group for an individual element, use the element parameters dialog (*Element menu : Edit : Element parameters* or *Shift+Ctrl+P Alt+G*)
